spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:h2:mem:attendance-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

event:
  service:
    url: http://localhost:8080/api/event